apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: k8s-demo
spec:
  acme:
    email: silaghi.adrian95@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: public-gw
                namespace: k8s-demo
                kind: Gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-example-com
  namespace: k8s-demo
spec:
  secretName: app-example-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - listspree.com
