apiVersion: v1
kind: Namespace
metadata:
  name: k8s-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: k8s-demo
data:
  PORT: "3000"
  PGHOST: "postgres.default.svc.cluster.local"
  PGPORT: "5432"
  PGUSER: "todo"
  PGDATABASE: "todoapp"
  REDIS_URL: "redis://redis.default.svc.cluster.local:6379"
  CACHE_TTL_SECONDS: "10"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: k8s-demo
type: Opaque
stringData:
  PGPASSWORD: "examplepassword"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: localhost:30500/k8s-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 60
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: k8s-demo
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gw
  namespace: k8s-demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: gateway-class
  addresses:
    - type: IPAddress
      value: 139.59.213.42
  listeners:
    - name: http
      hostname: listspree.com
      protocol: HTTP
      port: 80
      allowedRoutes: { namespaces: { from: Same } }
    - name: https
      hostname: listspree.com
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: listspree-com-tls
      allowedRoutes: { namespaces: { from: Same } }
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app
  namespace: k8s-demo
spec:
  parentRefs:
    - name: public-gw
      sectionName: https
  hostnames: [ "listspree.com" ]
  rules:
    - matches:
        - path: { type: PathPrefix, value: / }
      backendRefs:
        - name: app
          port: 3000

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-https
  namespace: k8s-demo
spec:
  parentRefs:
    - name: public-gw
      sectionName: http
  hostnames: [ "listspree.com" ]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect: { scheme: https, statusCode: 301 }

